apiVersion: v1
kind: ConfigMap
metadata:
  name: floodgate-config
data:
  config.yaml: |
    zerohop_enabled: true
    zerohop_channels:
      - "LongTurbo"
      - "LongFast"
      - "LongModerate"
      - "MediumFast"
      - "MediumSlow"
      - "ShortFast"
      - "ShortSlow"
      - "ShortTurbo"
    drop_enabled: false
    drop_channels: "zerohop_channels"
    drop_portnums: []
    grpc_port: 9000
    health_port: 8080
    topic_filter: "msh/#"
    stats_interval_s: 60
    log_level: "INFO"
    log_format: "text"
    stats_log: true
