apiVersion: v1
kind: Service
metadata:
  name: floodgate
  labels:
    app: floodgate
spec:
  type: ClusterIP
  selector:
    app: floodgate
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: grpc
